### PR TITLE
ScatteringBase complex_input and F

### PR DESCRIPTION
**Pull request by cyrusasfa**
* added `complex_input` to `ScatteringBase`
* added `F` to `ScatteringBase`
* initialize `sc_freq` in JTFS with `complex_input=True` and `F=F`

### CODE REVIEW

**Comment by lostanlen** [comment]
wait, `F`? no! `F` is just our nickname for frequential scattering's `T`
i don't think that a ScatteringBase object needs both a `F` and `T`
`complex_input=False` yes

initialize sc_freq in JTFS with complex_input=True and T=F

**Comment by cyrusasfa** [comment]
> wait, `F`? no! `F` is just our nickname for frequential scattering's `T` i don't think that a ScatteringBase object needs both a `F` and `T` `complex_input=False` yes
> 
> initialize sc_freq in JTFS with complex_input=True and T=F

Bon, good point. I guess the user never needs to know about the role of `T` when freq scattering is happening.

**Comment by MuawizChaudhary** [comment]
does this pass the one cuda test that was failing

**Comment by cyrusasfa** [comment]
> does this pass the one cuda test that was failing

NoI I will try to run it somewhere with 

> does this pass the one cuda test that was failing

can you run it on cuda? I think it was caused by my local configuration

**Pull request merged**
